# Generated by Django 3.1.3 on 2021-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_women_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.TextField(blank=True, verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='deadline',
            field=models.DateField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.CharField(max_length=255, verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
